"""add_interview_fields_to_pipeline

Revision ID: 235e3a881606
Revises: 2d682bdc9d5e
Create Date: 2026-06-28 23:41:36.379766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235e3a881606'
down_revision: Union[str, Sequence[str], None] = '2d682bdc9d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('interview_link', sa.String(), nullable=True))
    op.add_column('pipeline', sa.Column('interview_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pipeline', sa.Column('interview_timezone', sa.String(), nullable=True))
    op.add_column('pipeline', sa.Column('interview_message', sa.Text(), nullable=True))
    op.add_column('pipeline', sa.Column('interview_sent_at', sa.DateTime(timezone=True), nullable=True))
    
    # 1. Rename old enum type
    op.execute("ALTER TYPE hiring_manager_decision RENAME TO hiring_manager_decision_old")
    # 2. Create transition enum type
    op.execute("CREATE TYPE hiring_manager_decision AS ENUM ('PENDING', 'ACCEPTED', 'INTERVIEW_SENT', 'REJECTED')")
    # 3. Alter table column type to transition type
    op.execute("ALTER TABLE pipeline ALTER COLUMN hm_decision TYPE hiring_manager_decision USING hm_decision::text::hiring_manager_decision")
    # 4. Drop the old enum type
    op.execute("DROP TYPE hiring_manager_decision_old")
    
    # 5. Now update pipeline records from ACCEPTED to INTERVIEW_SENT
    op.execute("UPDATE pipeline SET hm_decision = 'INTERVIEW_SENT' WHERE hm_decision::text = 'ACCEPTED'")
    
    # 6. Re-create final enum type ('PENDING', 'INTERVIEW_SENT', 'REJECTED')
    op.execute("ALTER TYPE hiring_manager_decision RENAME TO hiring_manager_decision_temp")
    op.execute("CREATE TYPE hiring_manager_decision AS ENUM ('PENDING', 'INTERVIEW_SENT', 'REJECTED')")
    op.execute("ALTER TABLE pipeline ALTER COLUMN hm_decision TYPE hiring_manager_decision USING hm_decision::text::hiring_manager_decision")
    op.execute("DROP TYPE hiring_manager_decision_temp")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline', 'interview_sent_at')
    op.drop_column('pipeline', 'interview_message')
    op.drop_column('pipeline', 'interview_timezone')
    op.drop_column('pipeline', 'interview_datetime')
    op.drop_column('pipeline', 'interview_link')
    
    # 1. Rename old enum type
    op.execute("ALTER TYPE hiring_manager_decision RENAME TO hiring_manager_decision_old")
    # 2. Create transition enum type
    op.execute("CREATE TYPE hiring_manager_decision AS ENUM ('PENDING', 'ACCEPTED', 'INTERVIEW_SENT', 'REJECTED')")
    # 3. Alter column to transition type
    op.execute("ALTER TABLE pipeline ALTER COLUMN hm_decision TYPE hiring_manager_decision USING hm_decision::text::hiring_manager_decision")
    # 4. Drop old enum type
    op.execute("DROP TYPE hiring_manager_decision_old")
    
    # 5. Update pipeline records back
    op.execute("UPDATE pipeline SET hm_decision = 'ACCEPTED' WHERE hm_decision::text = 'INTERVIEW_SENT'")
    
    # 6. Re-create the final downgrade enum type ('PENDING', 'ACCEPTED', 'REJECTED')
    op.execute("ALTER TYPE hiring_manager_decision RENAME TO hiring_manager_decision_temp")
    op.execute("CREATE TYPE hiring_manager_decision AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED')")
    op.execute("ALTER TABLE pipeline ALTER COLUMN hm_decision TYPE hiring_manager_decision USING hm_decision::text::hiring_manager_decision")
    op.execute("DROP TYPE hiring_manager_decision_temp")
    # ### end Alembic commands ###
