"""add_hm_sharing_to_pipeline

Revision ID: e09cfb05c7aa
Revises: dfac98083d58
Create Date: 2026-06-28 15:34:20.203777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09cfb05c7aa'
down_revision: Union[str, Sequence[str], None] = 'dfac98083d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('shared_with_hiring_manager', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('pipeline', sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pipeline', sa.Column('hm_decision', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='hiring_manager_decision'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline', 'hm_decision')
    op.drop_column('pipeline', 'shared_at')
    op.drop_column('pipeline', 'shared_with_hiring_manager')
    # ### end Alembic commands ###
