"""make_resume_fields_nullable

Revision ID: fed858899178
Revises: 469aca59d215
Create Date: 2026-06-26 12:36:27.211892

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fed858899178"
down_revision: str | Sequence[str] | None = "469aca59d215"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("candidates", "resume_text", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "candidates", "resume_hash", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "candidates", "resume_hash", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "candidates", "resume_text", existing_type=sa.TEXT(), nullable=False
    )
    # ### end Alembic commands ###
